name: .NET workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install coverlet
      run: dotnet tool install --global coverlet.console

    - name: Install reportgenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResult/

    - name: Generate HTML report
      run: reportgenerator -reports:./FantasyGameTests/TestResult/coverage.cobertura.xml -targetdir:./FantasyGameTests/TestResult/CoverageReport/ -reporttypes:Html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: FantasyGameTests/TestResult/CoverageReport
